# Generated by Django 2.2.4 on 2019-08-14 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advert',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='advert',
            name='is_superuser',
        ),
    ]
