# Generated by Django 2.2.4 on 2019-08-15 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0002_auto_20190814_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='is_band',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='advert',
            name='max_age',
            field=models.IntegerField(default=99),
        ),
        migrations.AddField(
            model_name='advert',
            name='min_age',
            field=models.IntegerField(default=13),
        ),
    ]
