# Generated by Django 2.2.4 on 2019-08-15 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0003_auto_20190815_2201'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='advert',
            name='instruments',
            field=models.ManyToManyField(to='adverts.Instrument'),
        ),
    ]
